### ISSUE TITLE
Create a Template JS File

### ISSUE THREAD

**Issue by andrewzaldivar** [PAIR-code/datacardsplaybook#17]
As mentioned in #16, to improve clarity on how to run the Card Builder, especially when one wants to build a Data Card from a MD file, a template MD and HTML file that runs the script should be created.

**Comment by bramzandbelt** [comment]
I'd really appreciate a solution to this issue. Although I was able to build the `dist` directory with the scripts and styles, I was unable to convert a Data Card from Markdown to HTML, based on the README instructions. 

Specifically, putting the [code for conversion](https://github.com/PAIR-code/datacardsplaybook/blob/9c6545b1fe0e251aa7326969074bc84d5b87693e/labs/card-builder/README.md?plain=1#L59-L60) inside a file `New.js` and trying to run this as `node New.js` resulted in the following error

```
/home/bram/NS/TL/datacardsplaybook/labs/card-builder/dist/New.js:2
CardBuilder.markdownToHTMLCard(markdown);
^

ReferenceError: CardBuilder is not defined
    at Object.<anonymous> (/home/bram/NS/TL/datacardsplaybook/labs/card-builder/dist/New.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```
